name: Build and Push Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  build-web:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mario-pz
          password: ${{ secrets.GH_PAT }}

      - name: Build the Docker image
        run: docker build ./web -t ghcr.io/mario-pz/todo-guru/webapp:${GITHUB_REF##*/}

      - name: Push the Docker image
        run: docker push ghcr.io/mario-pz/todo-guru/webapp:${GITHUB_REF##*/}

  build-api:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: mario-pz
          password: ${{ secrets.GH_PAT }}

      - name: Build the Docker image
        run: docker build ./api -t ghcr.io/mario-pz/todo-guru/api:${GITHUB_REF##*/}

      - name: Push the Docker image
        run: docker push ghcr.io/mario-pz/todo-guru/api:${GITHUB_REF##*/}
